### ISSUE TITLE
Specify required plugins which a project needs

### ISSUE THREAD

**Issue by enzy** [manGoweb/MangoPress#120]
https://github.com/TGMPA/TGM-Plugin-Activation maybe?

Simplyfile into a neon file ~ `theme/schema/plugins.neon`

```
plugins:

  plugin-slug:
    name: plugin-name
    required: bool

  buddypress:
    name: BuddyPress
    required: true
```
